# .readthedocs.yaml
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/source/conf.py

# Build HTML; uncomment if you also want PDF/ePub artifacts
# formats:
#   - pdf
#   - epub

python:
  install:
    # 1) Install your package so autodoc can import it
    - method: pip
      path: 
    # 2) Install doc-only dependencies
    - requirements: docs/source/requirements.txt

