# .readthedocs.yaml
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  apt_packages:
    - libcairo2-dev
    - libpango1.0-dev
    - libgirepository1.0-dev
    - gir1.2-pango-1.0
    - gir1.2-harfbuzz-0.0
    - gir1.2-gdkpixbuf-2.0
    - ffmpeg
    - pkg-config
    - libffi-dev

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - method: pip
      path: .
    - requirements: docs/source/requirements.txt
